### Get all users
GET {{baseURL}}/api/users
    ?API_KEY={{API_KEY}} HTTP/1.1

### Get user

GET {{baseURL}}/api/user
    ?ID=1
    &API_KEY={{API_KEY}}

### Sign in

POST https://localhost:4433/api/signin  
    ?login=admin
    &password=admin
    &API_KEY={{API_KEY}}
Cookie: sessionID=6ab7cdea-1745-4272-a040-d7d0b3e1a9ed

### Sign up

POST https://localhost:4433/api/signup
    ?login=admin
    &password=admin
    &email=test
    &API_KEY={{API_KEY}}

### Update user

PUT https://localhost:4433/api/user/update
    ?ID=1
    &Name=Erzhan
    &API_KEY={{API_KEY}}


### Delete user

DELETE https://localhost:4433/api/user/delete
    ?ID=2
    &API_KEY={{API_KEY}}

