### Get all users
GET {{baseURL}}/api/users
    ?API_KEY={{API_KEY}} HTTP/1.1

### Get user

GET {{baseURL}}/api/user
    ?ID=1
    &API_KEY={{API_KEY}}

### Sign up

POST {{baseURL}}/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "login":"admin",
    "emal":"admin",
    "password":"admin"
}

### Sign in

POST {{baseURL}}/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "login":"admin",
    "password": "admin"
}
    
### Sign out

POST {{baseURL}}/api/auth/signout
    ?API_KEY={{API_KEY}}

### Update user

PUT {{baseURL}}/api/user/update
    ?ID=2
    &name=admin44
    &API_KEY={{API_KEY}}


### Delete user

DELETE {{baseURL}}/api/user/delete
    ?id=11

