version: "3"
services:
  db:
    image: mongo:3.4.5
    command: mongod --smallfiles --quiet --logpath=/dev/null --dbpath=/data/db
    volumes:
      - ./mongo_data:/data/db
  redis:
    image: redis:3.2.9
    command: redis-server
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOCKER: "true"
    volumes:
      - .:/var/www/app/:rw
      - /var/www/app/node_modules
    ports:
      - "8080:8080"
    restart: always
    links:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: go run main.go data.go
    volumes:
      - .:/var/www/app/:rw
    ports:
      - "3001:8081"
    environment:
      MONGO_URL: "db"
      REDIS_URL: "redis:6379"
    restart: always
    links:
      - db
      - redis
