### Get all posts
GET {{baseURL}}/api/posts
    ?API_KEY={{API_KEY}}

### Get post

GET {{baseURL}}/api/post
    ?ID=5
    &API_KEY={{API_KEY}}

### Create post

POST {{baseURL}}/api/post/create
    ?API_KEY={{API_KEY}}
Content-Type: application/json

{
    "description":"post2",
    "content":"content"
}

### Update post

PUT {{baseURL}}/api/post/update
    ?ID=2
    &description=updated
    &API_KEY={{API_KEY}}

### Delete post

DELETE {{baseURL}}/api/post/delete
    ?ID=4
    &API_KEY={{API_KEY}}