GET {{baseURL}}/api/comments
    ?ID=6
    &API_KEY={{API_KEY}}

### Create reply

POST {{baseURL}}/api/comment/add
    ?ID=6
    &API_KEY={{API_KEY}}
Content-Type: application/json

{
    "content":"cool reply"
}

### Update reply

PUT {{baseURL}}/api/comment/update
    ?ID=3
    &API_KEY={{API_KEY}}
Content-Type: application/json

{
    "content":"updated content"
}