### Create reply

POST {{baseURL}}/api/comment/add
    ?ID=2
    &API_KEY={{API_KEY}}
Content-Type: application/json

{
    "content":"cool reply"
}

### Update reply

PUT {{baseURL}}/api/comment/update
    ?ID=3
    &API_KEY={{API_KEY}}
Content-Type: application/json

{
    "content":"updated content"
}

### Delete reply

DELETE {{baseURL}}/api/comment/delete
    ?ID=6
    &API_KEY={{API_KEY}}