### Get all users
GET {{baseURL}}/api/users
    ?API_KEY={{API_KEY}} HTTP/1.1

### Get user

GET {{baseURL}}/api/user
    ?ID=3
    &API_KEY={{API_KEY}}

### Sign up

POST {{baseURL}}/api/signup
    ?login=test
    &password=test
    &email=test
    &API_KEY={{API_KEY}}

### Sign in

POST {{baseURL}}/api/signin  
    ?login=admin
    &password=admin
    &API_KEY={{API_KEY}}
    
### Sign out

POST {{baseURL}}/api/signout
    ?API_KEY={{API_KEY}}

### Update user

PUT https://localhost:4433/api/user/update
    ?ID=8
    &name=Erzhan
    &API_KEY={{API_KEY}}


### Delete user

DELETE https://localhost:4433/api/user/delete
    ?ID=8
    &API_KEY={{API_KEY}}

