### Get all users
GET {{baseURL}}/api/users
    ?API_KEY={{API_KEY}} HTTP/1.1

### Get user

GET {{baseURL}}/api/user
    ?ID=1
    &API_KEY={{API_KEY}}

### Sign up

POST {{baseURL}}/api/auth/signup
    ?login=admin
    &password=admin
    &email=admin
    &API_KEY={{API_KEY}}

### Sign in

POST {{baseURL}}/api/auth/signin  
    ?login=admin
    &password=admin
    &API_KEY={{API_KEY}}
    
### Sign out

POST {{baseURL}}/api/auth/signout
    ?API_KEY={{API_KEY}}

### Update user

PUT https://localhost:4433/api/user/update
    ?ID=2
    &name=admin44
    &API_KEY={{API_KEY}}


### Delete user

DELETE https://localhost:4433/api/user/delete
    ?ID=1
    &API_KEY={{API_KEY}}

